kind: pipeline
name: main-pipeline

platform:
    os: linux
    arch: amd64

steps:
- name: test
  image: golang
  commands:
  - go test -cover ./logging ./telemetry ./eth

services:
  - name: ganache
    image: trufflesuite/ganache-cli/
